export const DISPLAY_ALL_PRODUCT_SUCCESS = 'SUCCESS_TO_DISPLAY_PRODUCTS'
export const DISPLAY_ALL_PRODUCT_FAIL = 'FAIL_TO_ADD_DISPLAY_PRODUCTS'

export const SINGLE_PRODUCT_SUCCESS = 'SUCCESS_TO_GET_SINGLE_PRODUCT'
export const SINGLE_PRODCUT_FAIL = 'FAIL_TO_GET_SINGLE_PRODUCT'

export const INCREASE_QTY = 'INCREASE_ONE_BY_ONE'
export const DECRESE_QTY = 'DECREASE_ONE_BY_ONE'
export const SET_TOTAL_PRICE = 'CALCULATE_TOTAL_PRICE'


export const ADD_TO_CART = 'ADD_NEW_PRODUCT_TO_THE_CART'
export const ADD_TO_FAVORITE = 'ADD_NEW_PRODUCT_TO_THE_FAVOURITE_BUSCKET'

export const GET_CART_PRODUCTS = 'GET_CART_PRODUCT_FROM_USER_CART'
export const GET_FAVORITE_PRODUCTS = 'GET_FAVORITE_PRODUCT_FROM_USER_FAVORITE_BUSKET'

export const GET_BUSKET_PRODUCT_FAIL = 'FAIL_TO_GET_PRODUCT'

export const SET_TOTAL = 'SET_TOTAL_AMOUNT'


